import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  minify: prod,
  treeShaking: true,
  outfile: "main.js",
  metafile: true,
});

// The Hebra plugin (src/hebra, built by scripts/build-hebra.mjs into hebra-main.mjs) must
// never leak into the Obsidian bundle: it would drag the Hebra-only adapter, the `yaml`
// parser and the Hebra plugin API types into main.js.
function assertNoHebraCode(metafile) {
  const leaked = Object.values(metafile.outputs)
    .flatMap((output) => Object.keys(output.inputs))
    .filter((input) => /^src\/hebra\/|hebra-plugin-api|^node_modules\/yaml\//.test(input));
  if (leaked.length > 0) {
    console.error(`main.js bundles Hebra-only code: ${leaked.slice(0, 5).join(", ")}`);
    process.exit(1);
  }
}

if (prod) {
  const result = await context.rebuild();
  assertNoHebraCode(result.metafile);
  process.exit(0);
} else {
  await context.watch();
}
