import tsparser from "@typescript-eslint/parser";
import { defineConfig } from "eslint/config";
import obsidianmd from "eslint-plugin-obsidianmd";

export default defineConfig([
  {
    ignores: [
      "main.js",
      "node_modules/**",
      // Generated by `npm run build:hebra`.
      "hebra-main.mjs",
    ],
  },
  ...obsidianmd.configs.recommended,
  {
    files: ["**/*.ts"],
    languageOptions: {
      parser: tsparser,
      parserOptions: { project: "./tsconfig.json" },
    },
  },
  {
    // Build and test tooling runs in Node, never inside Obsidian.
    files: ["vitest.config.mts", "tests/**/*.ts"],
    rules: { "obsidianmd/no-nodejs-modules": "off" },
  },
  {
    // The Hebra plugin (src/hebra, its tests and its build script) is NOT an Obsidian
    // plugin: it runs inside Hebra's webview against HebraPluginApi, with no
    // `activeDocument`, `createEl` or Obsidian UI conventions, so the Obsidian-specific
    // rules do not apply there. The TypeScript and JavaScript rules still do.
    files: ["src/hebra/**/*.ts", "tests/hebra/**/*.ts", "scripts/**/*.mjs"],
    rules: Object.fromEntries(
      Object.keys(obsidianmd.rules).map((name) => [`obsidianmd/${name}`, "off"]),
    ),
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: { process: "readonly", console: "readonly" },
    },
  },
]);
